require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
 
RSpec/MultipleExpectations:
  Max: 2

RSpec/ExampleLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
